services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSocket port (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test/topic", "-m", "test"]
      interval: 10s
      timeout: 5s
      retries: 5

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"  # HTTP API port
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password  # Replace with a secure password
      - DOCKER_INFLUXDB_INIT_ORG=myorg  # Replace with your organization name
      - DOCKER_INFLUXDB_INIT_BUCKET=greenhouse  # Bucket name
      - DOCKER_INFLUXDB_INIT_RETENTION=7d  # Retention policy (optional)
    volumes:
      - ./influxdb/data:/var/lib/influxdb2

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"  # Node-RED UI port
    depends_on:
      - mqtt-broker
      - influxdb
    volumes:
      - ./nodered/data:/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Grafana UI port
    depends_on:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana